name       : python-pyee
version    : 6.0.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/1f/8e/ec9a9d07bcf316ebe8ef2c30b5c597988f5b8d324f8273c307843e63f49e/pyee-6.0.0.tar.gz : a9c9b60e8693a260dd942ef5a71358cfcbba15792d5e72caf0e3c891c4e91c3b
license    : MIT
component  : programming.python
summary    : pyee supplies an EventEmitter object similar to the EventEmitter from
    Node.js.
description: |
    Supplies an EventEmitter object similar to the EventEmitter from Node.js.
builddeps  :
    - python-vcversioner
rundeps    :
    - python3
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-setup_requires-deps.patch
build      : |
    %python3_setup
install    : |
    %python3_install
