name       : python-pyee
version    : 8.1.0
release    : 5
source     :
    - https://pypi.io/packages/source/p/pyee/pyee-8.1.0.tar.gz : 92dacc5bd2bdb8f95aa8dd2585d47ca1c4840e2adb95ccf90034d64f725bfd31
license    : MIT
component  : programming.python
summary    : pyee supplies an EventEmitter object similar to the EventEmitter from Node.js.
description: |
    Supplies an EventEmitter object similar to the EventEmitter from Node.js.
builddeps  :
    - pytest-runner
    - python-vcversioner
rundeps    :
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
