name       : python-pyee
version    : 3.0.3
release    : 1
source     :
    - https://files.pythonhosted.org/packages/79/3e/e4c510f85b964be266c7de068c362d04c63527ae79f1ccd088eed61d310a/pyee-3.0.3.tar.gz : 8b7afc97b340c652daa8b6d5ba7cd5177be7778a13a95577342035018327bfaf
license    : MIT
component  : programming.python
summary    : pyee supplies an EventEmitter object similar to the EventEmitter from Node.js.
description: |
    Supplies an EventEmitter object similar to the EventEmitter from Node.js.
builddeps  :
    - pkgconfig(python3)
    - pytest-runner
setup      : |
    %patch -p1 < $pkgfiles/Remove_vcversioner_creates_errors_with_solbuild.patch
build      : |
    %python3_setup
install    : |
    %python3_install
